name: Simple CI Pipeline

on:
  push:
    branches: [ main, Nghia/Merged ]
  pull_request:
    branches: [ main, Nghia/Merged ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Check versions
      run: |
        node --version
        npm --version

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: List build output
      run: ls -la dist/

    # Uncomment if you have tests
    # - name: Test
    #   run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
        retention-days: 7
